[workspace]
name = "jsr-dynamic-imports"
platforms = ["linux-64"]
authors = ["Brad Jones <brad@bjc.id.au>"]
channels = ["https://repo.prefix.dev/brads-forge", "conda-forge"]

[tasks]
init = "task init"

[tasks.code]
depends-on = ["init"]
cmd = "code ."

[dependencies]
cocogitto = ">=6.3.0,<7"
deno = ">=2.5.4,<2.6"
dprint = ">=0.50.2,<0.51"
lefthook = ">=1.13.6,<2"
nodejs = ">=24.9.0,<24.10"
task = ">=3.45.4,<4"
gh = ">=2.81.0,<3"
